#=============================================================================
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: magechiu < charles.r.chiu@gmail.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # tab
    default_indent = 4
    expand_tab = true

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "cycle"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30


[[layers]]
    name = 'lang#c'
    enable_clang_syntax_highlight = true

[[layers]]
    name = 'lang#rust'

[[layers]]
    name = 'lang#go'

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lsp"
    filetypes = [
        "rust"
    ]
    [layers.override_cmd]
        rust = ["rls"]

[[layers]]
    name = "format"


[[layers]]
    name = "checkers"
    show_cursor_error = false

[[layers]]
    name = "ui"
    enable_sidebar = false
    enable_scrollbar = false
    enable_indentline = true
    enable_cursorword = false
    indentline_char = '|'
    conceallevel = 0
    concealcursor = ''
    cursorword_delay = 50
    cursorword_exclude_filetype = []
    indentline_exclude_filetyps = []


[[layers]]
    name = "lang#vim"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "lang#dockerfile"

[[layers]]
    name = "github"

[[layers]]
    name = "colorscheme"

[options]
    colorscheme = "onedark"


[[layers]]
    name = "chat"
    
[options]
   enable_tabline_filetype_icon = false


[[layers]]
  name = "core#statusline"

[options]
    # options for statusline
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以禁用分割符号，
    # 分割符包括以下几种 "arrow", "curve", "slant", "fire", "nil"，默认为箭头 "arrow"
    # 设置活动窗口状态栏上的分割符号形状
    statusline_separator = "arrow"
    # 设置非活动窗口状态栏上的分割符号形状
    statusline_iseparator = "bar"

    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    buffer_index_type = 4
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1

    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    enable_statusline_mode = true

    # 状态栏左端部分的构成
    statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
    # 状态栏右端部分的构成
    statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time']
    # 列表可以由以下一项或多项组成

    # 'winnr' 当前窗口编号
    # 'syntax checking'
    # 'filename' 文件名
    # 'fileformat' 文件格式
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' 光标位置
    # 'percentage' 百分比
    # 'date' 日期
    # 'time' 时间
    # 'whitespace' 打开或者保存文件时，如果第 n 行的行尾有空格则显示 trailing[n]，并不能实时显示出行尾有空格的行号。
    # 'battery status' 电池状态
    # 'input method' 输入法
    # 'search status' 搜索状态



# This is an example for adding custom plugins lilydjwg/colorizer
[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = false
